image: 'maven:3-jdk-8'
stages:
  - test
  - build
services:
  - 'mysql:5.5'
  - 'mongo:3.4-jessie'
variables:
  MYSQL_DATABASE: "userdatabase"
  MYSQL_URL: "jdbc:mysql://mysql/userdatabase"
  MYSQL_USER: "approot"
  MYSQL_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
  FAV_MONGO_DB_NAME: "favouritesdb"
  FAV_MONGO_DB_URL: "mongodb://mongo/favouritesdb"
  MR_MONGO_DB_NAME: "recommendationdb"
  MR_MONGO_DB_URL: "mongodb://mongo/recommendationdb"
cache:
  paths:
    - .m2/repository
    - target
maven-test:
  stage: test
  script: "mvn test"
maven-build:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
